baseURL = 'https://tews.dev/'
languageCode = 'de-de'
title = 'tews.dev'
theme = ['hugo-video', 'paper']

[params]
  color = 'linen'                           # linen, wheat, gray, light

  github = 'mewsen'

  name = 'Michael Tews'
  bio = 'Softwareentwickler'
