baseURL = 'https://tews.dev/'
languageCode = 'de-de'
title = 'tews.dev'
theme = ['hugo-video', 'paper']

[params]
  color = 'linen'                           # linen, wheat, gray, light

  twitter = 'mewsen'
  github = 'mewsen'
  rss = false

  name = 'Michael Tews'
  bio = 'Software Entwickler'
